// <auto-generated />
using System;
using ApiEasyStay.Properties.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiEasyStay.Properties.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830213750_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfigPerfilEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<bool>("PerfilInterno")
                        .HasColumnType("boolean")
                        .HasColumnName("perfil_interno");

                    b.HasKey("Id")
                        .HasName("pk_config_perfis");

                    b.ToTable("config_perfis", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfigPerfilPermissaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permissao_id");

                    b.HasKey("Id")
                        .HasName("pk_config_perfil_permissoes");

                    b.HasIndex("PermissaoId")
                        .HasDatabaseName("ix_config_perfil_permissoes_permissao_id");

                    b.HasIndex("PerfilId", "PermissaoId")
                        .IsUnique()
                        .HasDatabaseName("ix_config_perfil_permissoes_perfil_id_permissao_id");

                    b.ToTable("config_perfil_permissoes", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfigPermissaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_config_permissoes");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_config_permissoes_nome");

                    b.ToTable("config_permissoes", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfiguracaoSistemaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorPrimariaModoClaro")
                        .HasColumnType("text")
                        .HasColumnName("cor_primaria_modo_claro");

                    b.Property<string>("CorPrimariaModoEscuro")
                        .HasColumnType("text")
                        .HasColumnName("cor_primaria_modo_escuro");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("ModoEscuroPadrao")
                        .HasColumnType("boolean")
                        .HasColumnName("modo_escuro_padrao");

                    b.Property<string>("NomeSistema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_sistema");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes_sistema");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_configuracoes_sistema_empresa_id");

                    b.ToTable("configuracoes_sistema", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.EmpresaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<string>("Documento")
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.LancamentoFinanceiroEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lancamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_lancamentos_financeiros");

                    b.HasIndex("ReservaId")
                        .HasDatabaseName("ix_lancamentos_financeiros_reserva_id");

                    b.ToTable("lancamentos_financeiros", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.QuartoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoDiaria")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_diaria");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoQuartoBooking")
                        .HasColumnType("text")
                        .HasColumnName("tipo_quarto_booking");

                    b.HasKey("Id")
                        .HasName("pk_quartos");

                    b.ToTable("quartos", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ReservaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_saida");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("QuantidadeHospedes")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_hospedes");

                    b.Property<Guid>("QuartoId")
                        .HasColumnType("uuid")
                        .HasColumnName("quarto_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_reservas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_reservas_cliente_id");

                    b.HasIndex("CriadoPorUsuarioId")
                        .HasDatabaseName("ix_reservas_criado_por_usuario_id");

                    b.HasIndex("QuartoId")
                        .HasDatabaseName("ix_reservas_quarto_id");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.SincronizacaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dados")
                        .HasColumnType("text")
                        .HasColumnName("dados");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<DateTime?>("DataHoraSincronizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_sincronizado");

                    b.Property<string>("Entidade")
                        .HasColumnType("text")
                        .HasColumnName("entidade");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<string>("Operacao")
                        .HasColumnType("text")
                        .HasColumnName("operacao");

                    b.HasKey("Id")
                        .HasName("pk_sincronizacoes");

                    b.ToTable("sincronizacoes", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataHoraAtualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_atualizado");

                    b.Property<DateTime>("DataHoraCriado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_criado");

                    b.Property<DateTime?>("DataHoraDeletado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_deletado");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Senha")
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuarios_perfil_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfigPerfilPermissaoEntity", b =>
                {
                    b.HasOne("ApiEasyStay.Properties.Entities.v1.ConfigPerfilEntity", "Perfil")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_config_perfil_permissoes_config_perfis_perfil_id");

                    b.HasOne("ApiEasyStay.Properties.Entities.v1.ConfigPermissaoEntity", "Permissao")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_config_perfil_permissoes_config_permissoes_permissao_id");

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfiguracaoSistemaEntity", b =>
                {
                    b.HasOne("ApiEasyStay.Properties.Entities.v1.EmpresaEntity", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_configuracoes_sistema_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.LancamentoFinanceiroEntity", b =>
                {
                    b.HasOne("ApiEasyStay.Properties.Entities.v1.ReservaEntity", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lancamentos_financeiros_reservas_reserva_id");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ReservaEntity", b =>
                {
                    b.HasOne("ApiEasyStay.Properties.Entities.v1.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_clientes_cliente_id");

                    b.HasOne("ApiEasyStay.Properties.Entities.v1.UsuarioEntity", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_usuarios_criado_por_usuario_id");

                    b.HasOne("ApiEasyStay.Properties.Entities.v1.QuartoEntity", "Quarto")
                        .WithMany()
                        .HasForeignKey("QuartoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_quartos_quarto_id");

                    b.Navigation("Cliente");

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.UsuarioEntity", b =>
                {
                    b.HasOne("ApiEasyStay.Properties.Entities.v1.ConfigPerfilEntity", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_config_perfil_perfil_id");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfigPerfilEntity", b =>
                {
                    b.Navigation("PerfilPermissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ApiEasyStay.Properties.Entities.v1.ConfigPermissaoEntity", b =>
                {
                    b.Navigation("PerfilPermissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
